# Version of docker-compose
version: "3"
volumes:
  postgres_data:
    driver: local
# Containers we are going to run
services:
  web:
    build:
      context: .
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: rushing_dev
      PGHOST: db
      PGPORT: 5432
      MIX_ENV: dev
    ports:
      - "4000:4000"
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rushing_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data